backend:
  name: gitea
  repo: tro2789/preroll.io
  branch: main
  app_id: 7bacd47f-7c2b-4c42-9a4a-54095fd37afa
  api_root: https://gitea.tohareprod.com/api/v1
  base_url: https://gitea.tohareprod.com
  auth_endpoint: login/oauth/authorize

media_folder: public/images/blog
public_folder: /images/blog

collections:
  - name: blog
    label: Blog Posts
    label_singular: Blog Post
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - {
          label: Date,
          name: date,
          widget: datetime,
          date_format: "YYYY-MM-DD",
          time_format: false,
          format: "YYYY-MM-DD",
          picker_utc: true,
        }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Tags, name: tags, widget: list }
      - { label: Author, name: author, widget: string, default: "Trevor O'Hare" }
      - { label: Featured image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
